language: node_js

node_js:
  - "6"
  - "8"
  - "10"

install:
  - export NODE_VER=$(node -v)
  - NODE_VER=${NODE_VER:1:2}
  - echo "NODE_VER=${NODE_VER}"
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "BRANCH=${BRANCH}"
  - if [ "${NODE_VER}" -ge 10 ]; then
    if [[ "${BRANCH}" == greenkeeper/* ]]; then
      echo npm install
      npm install
    else
      echo npm ci
      npm ci
    fi
  else
    echo npm install
    npm install
  fi

script:
  - make

after_script:
  - npm run coverage:coveralls
