name: Build Workflow
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 16.x
    steps:
      - name: "Set up Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node-version }}"
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Build package"
        run: "npm run release:build"
      - name: "Coverage Report"
        run: |
          npm run coverage:report
          npm run coverage:html
          npm run coverage:codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/
          fail_ci_if_error: true
          verbose: true
